// auth.constants.ts
export const AUTH = {
    OTP_COOKIE_NAME: 'otp_token',
    AT_COOKIE_NAME: 'access_token',
    JWT_OTP_PURPOSE: 'otp',
    JWT_SESSION_PURPOSE: 'session',
    EXPIRED_AT_DURATION: 60 * 60000,
    SET_PASS_EXPIRED_AT_DURATION: 1440 * 60000,
    USED_TOKEN: '_USED_',
  }
  export const AUTH_ERR = {
    USER_NOT_FOUND_SIGN_UP_FIRST: 'USER_NOT_FOUND_SIGN_UP_FIRST',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    INACTIVE_ACCOUNT: 'INACTIVE_ACCOUNT',
    INACTIVE_TOKEN: 'INACTIVE_TOKEN',
    OTP_EXPIRED: 'OTP_EXPIRED',
    INVALID_OTP: 'INVALID_OTP',
    INVALID_SESSION: 'INVALID_SESSION',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    OTP_THREE_FAILED_TRIAL: 'OTP_THREE_FAILED_TRIAL', //3 trials password, user is blocked , please contact the
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    // administrator
  }